// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/Auth.proto

package com.mc.netty.probuffer;

public final class AuthProtos {
  private AuthProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.LoginRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string memberId = 1;</code>
     */
    java.lang.String getMemberId();
    /**
     * <code>string memberId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();

    /**
     * <code>string token = 2;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 2;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code wuage.LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageLite<
          LoginRequest, LoginRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.LoginRequest)
      LoginRequestOrBuilder {
    private LoginRequest() {
      memberId_ = "";
      token_ = "";
    }
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private java.lang.String memberId_;
    /**
     * <code>string memberId = 1;</code>
     */
    public java.lang.String getMemberId() {
      return memberId_;
    }
    /**
     * <code>string memberId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(memberId_);
    }
    /**
     * <code>string memberId = 1;</code>
     */
    private void setMemberId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      memberId_ = value;
    }
    /**
     * <code>string memberId = 1;</code>
     */
    private void clearMemberId() {
      
      memberId_ = getDefaultInstance().getMemberId();
    }
    /**
     * <code>string memberId = 1;</code>
     */
    private void setMemberIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      memberId_ = value.toStringUtf8();
    }

    public static final int TOKEN_FIELD_NUMBER = 2;
    private java.lang.String token_;
    /**
     * <code>string token = 2;</code>
     */
    public java.lang.String getToken() {
      return token_;
    }
    /**
     * <code>string token = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(token_);
    }
    /**
     * <code>string token = 2;</code>
     */
    private void setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
    }
    /**
     * <code>string token = 2;</code>
     */
    private void clearToken() {
      
      token_ = getDefaultInstance().getToken();
    }
    /**
     * <code>string token = 2;</code>
     */
    private void setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!memberId_.isEmpty()) {
        output.writeString(1, getMemberId());
      }
      if (!token_.isEmpty()) {
        output.writeString(2, getToken());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!memberId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMemberId());
      }
      if (!token_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getToken());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.AuthProtos.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.AuthProtos.LoginRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.LoginRequest)
        com.mc.netty.probuffer.AuthProtos.LoginRequestOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.AuthProtos.LoginRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string memberId = 1;</code>
       */
      public java.lang.String getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>string memberId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        return instance.getMemberIdBytes();
      }
      /**
       * <code>string memberId = 1;</code>
       */
      public Builder setMemberId(
          java.lang.String value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>string memberId = 1;</code>
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }
      /**
       * <code>string memberId = 1;</code>
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMemberIdBytes(value);
        return this;
      }

      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        return instance.getToken();
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        return instance.getTokenBytes();
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setToken(value);
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder clearToken() {
        copyOnWrite();
        instance.clearToken();
        return this;
      }
      /**
       * <code>string token = 2;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.LoginRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.AuthProtos.LoginRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.AuthProtos.LoginRequest other = (com.mc.netty.probuffer.AuthProtos.LoginRequest) arg1;
          memberId_ = visitor.visitString(!memberId_.isEmpty(), memberId_,
              !other.memberId_.isEmpty(), other.memberId_);
          token_ = visitor.visitString(!token_.isEmpty(), token_,
              !other.token_.isEmpty(), other.token_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  memberId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  token_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.AuthProtos.LoginRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.LoginRequest)
    private static final com.mc.netty.probuffer.AuthProtos.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.AuthProtos.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginRequest> PARSER;

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.LoginResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    boolean hasCommonInfo();
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    com.mc.netty.probuffer.CommonProtos.Common getCommonInfo();

    /**
     * <code>string memberId = 2;</code>
     */
    java.lang.String getMemberId();
    /**
     * <code>string memberId = 2;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();
  }
  /**
   * Protobuf type {@code wuage.LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageLite<
          LoginResponse, LoginResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.LoginResponse)
      LoginResponseOrBuilder {
    private LoginResponse() {
      memberId_ = "";
    }
    public static final int COMMONINFO_FIELD_NUMBER = 1;
    private com.mc.netty.probuffer.CommonProtos.Common commonInfo_;
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    public boolean hasCommonInfo() {
      return commonInfo_ != null;
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    public com.mc.netty.probuffer.CommonProtos.Common getCommonInfo() {
      return commonInfo_ == null ? com.mc.netty.probuffer.CommonProtos.Common.getDefaultInstance() : commonInfo_;
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void setCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
      if (value == null) {
        throw new NullPointerException();
      }
      commonInfo_ = value;
      
      }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void setCommonInfo(
        com.mc.netty.probuffer.CommonProtos.Common.Builder builderForValue) {
      commonInfo_ = builderForValue.build();
      
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void mergeCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
      if (commonInfo_ != null &&
          commonInfo_ != com.mc.netty.probuffer.CommonProtos.Common.getDefaultInstance()) {
        commonInfo_ =
          com.mc.netty.probuffer.CommonProtos.Common.newBuilder(commonInfo_).mergeFrom(value).buildPartial();
      } else {
        commonInfo_ = value;
      }
      
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void clearCommonInfo() {  commonInfo_ = null;
      
    }

    public static final int MEMBERID_FIELD_NUMBER = 2;
    private java.lang.String memberId_;
    /**
     * <code>string memberId = 2;</code>
     */
    public java.lang.String getMemberId() {
      return memberId_;
    }
    /**
     * <code>string memberId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(memberId_);
    }
    /**
     * <code>string memberId = 2;</code>
     */
    private void setMemberId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      memberId_ = value;
    }
    /**
     * <code>string memberId = 2;</code>
     */
    private void clearMemberId() {
      
      memberId_ = getDefaultInstance().getMemberId();
    }
    /**
     * <code>string memberId = 2;</code>
     */
    private void setMemberIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      memberId_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commonInfo_ != null) {
        output.writeMessage(1, getCommonInfo());
      }
      if (!memberId_.isEmpty()) {
        output.writeString(2, getMemberId());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (commonInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommonInfo());
      }
      if (!memberId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getMemberId());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.AuthProtos.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.AuthProtos.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.AuthProtos.LoginResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.LoginResponse)
        com.mc.netty.probuffer.AuthProtos.LoginResponseOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.AuthProtos.LoginResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public boolean hasCommonInfo() {
        return instance.hasCommonInfo();
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public com.mc.netty.probuffer.CommonProtos.Common getCommonInfo() {
        return instance.getCommonInfo();
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder setCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
        copyOnWrite();
        instance.setCommonInfo(value);
        return this;
        }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder setCommonInfo(
          com.mc.netty.probuffer.CommonProtos.Common.Builder builderForValue) {
        copyOnWrite();
        instance.setCommonInfo(builderForValue);
        return this;
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder mergeCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
        copyOnWrite();
        instance.mergeCommonInfo(value);
        return this;
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder clearCommonInfo() {  copyOnWrite();
        instance.clearCommonInfo();
        return this;
      }

      /**
       * <code>string memberId = 2;</code>
       */
      public java.lang.String getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <code>string memberId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        return instance.getMemberIdBytes();
      }
      /**
       * <code>string memberId = 2;</code>
       */
      public Builder setMemberId(
          java.lang.String value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <code>string memberId = 2;</code>
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }
      /**
       * <code>string memberId = 2;</code>
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMemberIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.LoginResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.AuthProtos.LoginResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.AuthProtos.LoginResponse other = (com.mc.netty.probuffer.AuthProtos.LoginResponse) arg1;
          commonInfo_ = visitor.visitMessage(commonInfo_, other.commonInfo_);
          memberId_ = visitor.visitString(!memberId_.isEmpty(), memberId_,
              !other.memberId_.isEmpty(), other.memberId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.mc.netty.probuffer.CommonProtos.Common.Builder subBuilder = null;
                  if (commonInfo_ != null) {
                    subBuilder = commonInfo_.toBuilder();
                  }
                  commonInfo_ = input.readMessage(com.mc.netty.probuffer.CommonProtos.Common.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(commonInfo_);
                    commonInfo_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  memberId_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.AuthProtos.LoginResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.LoginResponse)
    private static final com.mc.netty.probuffer.AuthProtos.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LoginResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.AuthProtos.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginResponse> PARSER;

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
