// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/Common.proto

package com.mc.netty.probuffer;

public final class CommonProtos {
  private CommonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CommonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.Common)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 错误码，0为正确，非0均为请求异常
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    int getErrCode();

    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    java.lang.String getErrDesc();
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrDescBytes();

    /**
     * <pre>
     * 时间戳，数据返回的本地时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * <pre>
   * 所有接口中的通用模块，该模块为所有接口必填项
   * </pre>
   *
   * Protobuf type {@code wuage.Common}
   */
  public  static final class Common extends
      com.google.protobuf.GeneratedMessageLite<
          Common, Common.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.Common)
      CommonOrBuilder {
    private Common() {
      errDesc_ = "";
    }
    public static final int ERRCODE_FIELD_NUMBER = 1;
    private int errCode_;
    /**
     * <pre>
     * 错误码，0为正确，非0均为请求异常
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    public int getErrCode() {
      return errCode_;
    }
    /**
     * <pre>
     * 错误码，0为正确，非0均为请求异常
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    private void setErrCode(int value) {
      
      errCode_ = value;
    }
    /**
     * <pre>
     * 错误码，0为正确，非0均为请求异常
     * </pre>
     *
     * <code>int32 errCode = 1;</code>
     */
    private void clearErrCode() {
      
      errCode_ = 0;
    }

    public static final int ERRDESC_FIELD_NUMBER = 2;
    private java.lang.String errDesc_;
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    public java.lang.String getErrDesc() {
      return errDesc_;
    }
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrDescBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(errDesc_);
    }
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    private void setErrDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errDesc_ = value;
    }
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    private void clearErrDesc() {
      
      errDesc_ = getDefaultInstance().getErrDesc();
    }
    /**
     * <pre>
     * 错误提醒内容，配合errno使用
     * </pre>
     *
     * <code>string errDesc = 2;</code>
     */
    private void setErrDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errDesc_ = value.toStringUtf8();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <pre>
     * 时间戳，数据返回的本地时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳，数据返回的本地时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * 时间戳，数据返回的本地时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0L;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCode_ != 0) {
        output.writeInt32(1, errCode_);
      }
      if (!errDesc_.isEmpty()) {
        output.writeString(2, getErrDesc());
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (errCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, errCode_);
      }
      if (!errDesc_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getErrDesc());
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.CommonProtos.Common parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.CommonProtos.Common prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * 所有接口中的通用模块，该模块为所有接口必填项
     * </pre>
     *
     * Protobuf type {@code wuage.Common}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.CommonProtos.Common, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.Common)
        com.mc.netty.probuffer.CommonProtos.CommonOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.CommonProtos.Common.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 错误码，0为正确，非0均为请求异常
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public int getErrCode() {
        return instance.getErrCode();
      }
      /**
       * <pre>
       * 错误码，0为正确，非0均为请求异常
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public Builder setErrCode(int value) {
        copyOnWrite();
        instance.setErrCode(value);
        return this;
      }
      /**
       * <pre>
       * 错误码，0为正确，非0均为请求异常
       * </pre>
       *
       * <code>int32 errCode = 1;</code>
       */
      public Builder clearErrCode() {
        copyOnWrite();
        instance.clearErrCode();
        return this;
      }

      /**
       * <pre>
       * 错误提醒内容，配合errno使用
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public java.lang.String getErrDesc() {
        return instance.getErrDesc();
      }
      /**
       * <pre>
       * 错误提醒内容，配合errno使用
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrDescBytes() {
        return instance.getErrDescBytes();
      }
      /**
       * <pre>
       * 错误提醒内容，配合errno使用
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder setErrDesc(
          java.lang.String value) {
        copyOnWrite();
        instance.setErrDesc(value);
        return this;
      }
      /**
       * <pre>
       * 错误提醒内容，配合errno使用
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder clearErrDesc() {
        copyOnWrite();
        instance.clearErrDesc();
        return this;
      }
      /**
       * <pre>
       * 错误提醒内容，配合errno使用
       * </pre>
       *
       * <code>string errDesc = 2;</code>
       */
      public Builder setErrDescBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setErrDescBytes(value);
        return this;
      }

      /**
       * <pre>
       * 时间戳，数据返回的本地时间戳
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * 时间戳，数据返回的本地时间戳
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * 时间戳，数据返回的本地时间戳
       * </pre>
       *
       * <code>int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.Common)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.CommonProtos.Common();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.CommonProtos.Common other = (com.mc.netty.probuffer.CommonProtos.Common) arg1;
          errCode_ = visitor.visitInt(errCode_ != 0, errCode_,
              other.errCode_ != 0, other.errCode_);
          errDesc_ = visitor.visitString(!errDesc_.isEmpty(), errDesc_,
              !other.errDesc_.isEmpty(), other.errDesc_);
          timestamp_ = visitor.visitLong(timestamp_ != 0L, timestamp_,
              other.timestamp_ != 0L, other.timestamp_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  errCode_ = input.readInt32();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  errDesc_ = s;
                  break;
                }
                case 24: {

                  timestamp_ = input.readInt64();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.CommonProtos.Common.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.Common)
    private static final com.mc.netty.probuffer.CommonProtos.Common DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Common();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.CommonProtos.Common getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Common> PARSER;

    public static com.google.protobuf.Parser<Common> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
