// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/IMUser.proto

package com.mc.netty.probuffer;

public final class IMUserProtos {
  private IMUserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.UserInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    java.lang.String getMemberId();
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes();

    /**
     * <code>string nick = 2;</code>
     */
    java.lang.String getNick();
    /**
     * <code>string nick = 2;</code>
     */
    com.google.protobuf.ByteString
        getNickBytes();

    /**
     * <code>string avatar = 3;</code>
     */
    java.lang.String getAvatar();
    /**
     * <code>string avatar = 3;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();

    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    java.lang.String getExtension();
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    com.google.protobuf.ByteString
        getExtensionBytes();

    /**
     * <pre>
     * 版本控制
     * </pre>
     *
     * <code>int64 lastUpdateTime = 5;</code>
     */
    long getLastUpdateTime();

    /**
     * <pre>
     * 是否为活动状态，可能被屏蔽
     * </pre>
     *
     * <code>bool isActive = 6;</code>
     */
    boolean getIsActive();
  }
  /**
   * Protobuf type {@code wuage.UserInfo}
   */
  public  static final class UserInfo extends
      com.google.protobuf.GeneratedMessageLite<
          UserInfo, UserInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.UserInfo)
      UserInfoOrBuilder {
    private UserInfo() {
      memberId_ = "";
      nick_ = "";
      avatar_ = "";
      extension_ = "";
    }
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private java.lang.String memberId_;
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    public java.lang.String getMemberId() {
      return memberId_;
    }
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(memberId_);
    }
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    private void setMemberId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      memberId_ = value;
    }
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    private void clearMemberId() {
      
      memberId_ = getDefaultInstance().getMemberId();
    }
    /**
     * <pre>
     * 成员id
     * </pre>
     *
     * <code>string memberId = 1;</code>
     */
    private void setMemberIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      memberId_ = value.toStringUtf8();
    }

    public static final int NICK_FIELD_NUMBER = 2;
    private java.lang.String nick_;
    /**
     * <code>string nick = 2;</code>
     */
    public java.lang.String getNick() {
      return nick_;
    }
    /**
     * <code>string nick = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNickBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(nick_);
    }
    /**
     * <code>string nick = 2;</code>
     */
    private void setNick(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nick_ = value;
    }
    /**
     * <code>string nick = 2;</code>
     */
    private void clearNick() {
      
      nick_ = getDefaultInstance().getNick();
    }
    /**
     * <code>string nick = 2;</code>
     */
    private void setNickBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nick_ = value.toStringUtf8();
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private java.lang.String avatar_;
    /**
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      return avatar_;
    }
    /**
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(avatar_);
    }
    /**
     * <code>string avatar = 3;</code>
     */
    private void setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
    }
    /**
     * <code>string avatar = 3;</code>
     */
    private void clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
    }
    /**
     * <code>string avatar = 3;</code>
     */
    private void setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value.toStringUtf8();
    }

    public static final int EXTENSION_FIELD_NUMBER = 4;
    private java.lang.String extension_;
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    public java.lang.String getExtension() {
      return extension_;
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extension_);
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    private void setExtension(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extension_ = value;
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    private void clearExtension() {
      
      extension_ = getDefaultInstance().getExtension();
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 4;</code>
     */
    private void setExtensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extension_ = value.toStringUtf8();
    }

    public static final int LASTUPDATETIME_FIELD_NUMBER = 5;
    private long lastUpdateTime_;
    /**
     * <pre>
     * 版本控制
     * </pre>
     *
     * <code>int64 lastUpdateTime = 5;</code>
     */
    public long getLastUpdateTime() {
      return lastUpdateTime_;
    }
    /**
     * <pre>
     * 版本控制
     * </pre>
     *
     * <code>int64 lastUpdateTime = 5;</code>
     */
    private void setLastUpdateTime(long value) {
      
      lastUpdateTime_ = value;
    }
    /**
     * <pre>
     * 版本控制
     * </pre>
     *
     * <code>int64 lastUpdateTime = 5;</code>
     */
    private void clearLastUpdateTime() {
      
      lastUpdateTime_ = 0L;
    }

    public static final int ISACTIVE_FIELD_NUMBER = 6;
    private boolean isActive_;
    /**
     * <pre>
     * 是否为活动状态，可能被屏蔽
     * </pre>
     *
     * <code>bool isActive = 6;</code>
     */
    public boolean getIsActive() {
      return isActive_;
    }
    /**
     * <pre>
     * 是否为活动状态，可能被屏蔽
     * </pre>
     *
     * <code>bool isActive = 6;</code>
     */
    private void setIsActive(boolean value) {
      
      isActive_ = value;
    }
    /**
     * <pre>
     * 是否为活动状态，可能被屏蔽
     * </pre>
     *
     * <code>bool isActive = 6;</code>
     */
    private void clearIsActive() {
      
      isActive_ = false;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!memberId_.isEmpty()) {
        output.writeString(1, getMemberId());
      }
      if (!nick_.isEmpty()) {
        output.writeString(2, getNick());
      }
      if (!avatar_.isEmpty()) {
        output.writeString(3, getAvatar());
      }
      if (!extension_.isEmpty()) {
        output.writeString(4, getExtension());
      }
      if (lastUpdateTime_ != 0L) {
        output.writeInt64(5, lastUpdateTime_);
      }
      if (isActive_ != false) {
        output.writeBool(6, isActive_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!memberId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getMemberId());
      }
      if (!nick_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getNick());
      }
      if (!avatar_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getAvatar());
      }
      if (!extension_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getExtension());
      }
      if (lastUpdateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, lastUpdateTime_);
      }
      if (isActive_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isActive_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.IMUserProtos.UserInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.IMUserProtos.UserInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.UserInfo)
        com.mc.netty.probuffer.IMUserProtos.UserInfoOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.IMUserProtos.UserInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 成员id
       * </pre>
       *
       * <code>string memberId = 1;</code>
       */
      public java.lang.String getMemberId() {
        return instance.getMemberId();
      }
      /**
       * <pre>
       * 成员id
       * </pre>
       *
       * <code>string memberId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes() {
        return instance.getMemberIdBytes();
      }
      /**
       * <pre>
       * 成员id
       * </pre>
       *
       * <code>string memberId = 1;</code>
       */
      public Builder setMemberId(
          java.lang.String value) {
        copyOnWrite();
        instance.setMemberId(value);
        return this;
      }
      /**
       * <pre>
       * 成员id
       * </pre>
       *
       * <code>string memberId = 1;</code>
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }
      /**
       * <pre>
       * 成员id
       * </pre>
       *
       * <code>string memberId = 1;</code>
       */
      public Builder setMemberIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMemberIdBytes(value);
        return this;
      }

      /**
       * <code>string nick = 2;</code>
       */
      public java.lang.String getNick() {
        return instance.getNick();
      }
      /**
       * <code>string nick = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNickBytes() {
        return instance.getNickBytes();
      }
      /**
       * <code>string nick = 2;</code>
       */
      public Builder setNick(
          java.lang.String value) {
        copyOnWrite();
        instance.setNick(value);
        return this;
      }
      /**
       * <code>string nick = 2;</code>
       */
      public Builder clearNick() {
        copyOnWrite();
        instance.clearNick();
        return this;
      }
      /**
       * <code>string nick = 2;</code>
       */
      public Builder setNickBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNickBytes(value);
        return this;
      }

      /**
       * <code>string avatar = 3;</code>
       */
      public java.lang.String getAvatar() {
        return instance.getAvatar();
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        return instance.getAvatarBytes();
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        copyOnWrite();
        instance.setAvatar(value);
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder clearAvatar() {
        copyOnWrite();
        instance.clearAvatar();
        return this;
      }
      /**
       * <code>string avatar = 3;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAvatarBytes(value);
        return this;
      }

      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 4;</code>
       */
      public java.lang.String getExtension() {
        return instance.getExtension();
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExtensionBytes() {
        return instance.getExtensionBytes();
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 4;</code>
       */
      public Builder setExtension(
          java.lang.String value) {
        copyOnWrite();
        instance.setExtension(value);
        return this;
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 4;</code>
       */
      public Builder clearExtension() {
        copyOnWrite();
        instance.clearExtension();
        return this;
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 4;</code>
       */
      public Builder setExtensionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtensionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 版本控制
       * </pre>
       *
       * <code>int64 lastUpdateTime = 5;</code>
       */
      public long getLastUpdateTime() {
        return instance.getLastUpdateTime();
      }
      /**
       * <pre>
       * 版本控制
       * </pre>
       *
       * <code>int64 lastUpdateTime = 5;</code>
       */
      public Builder setLastUpdateTime(long value) {
        copyOnWrite();
        instance.setLastUpdateTime(value);
        return this;
      }
      /**
       * <pre>
       * 版本控制
       * </pre>
       *
       * <code>int64 lastUpdateTime = 5;</code>
       */
      public Builder clearLastUpdateTime() {
        copyOnWrite();
        instance.clearLastUpdateTime();
        return this;
      }

      /**
       * <pre>
       * 是否为活动状态，可能被屏蔽
       * </pre>
       *
       * <code>bool isActive = 6;</code>
       */
      public boolean getIsActive() {
        return instance.getIsActive();
      }
      /**
       * <pre>
       * 是否为活动状态，可能被屏蔽
       * </pre>
       *
       * <code>bool isActive = 6;</code>
       */
      public Builder setIsActive(boolean value) {
        copyOnWrite();
        instance.setIsActive(value);
        return this;
      }
      /**
       * <pre>
       * 是否为活动状态，可能被屏蔽
       * </pre>
       *
       * <code>bool isActive = 6;</code>
       */
      public Builder clearIsActive() {
        copyOnWrite();
        instance.clearIsActive();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.UserInfo)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.IMUserProtos.UserInfo();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.IMUserProtos.UserInfo other = (com.mc.netty.probuffer.IMUserProtos.UserInfo) arg1;
          memberId_ = visitor.visitString(!memberId_.isEmpty(), memberId_,
              !other.memberId_.isEmpty(), other.memberId_);
          nick_ = visitor.visitString(!nick_.isEmpty(), nick_,
              !other.nick_.isEmpty(), other.nick_);
          avatar_ = visitor.visitString(!avatar_.isEmpty(), avatar_,
              !other.avatar_.isEmpty(), other.avatar_);
          extension_ = visitor.visitString(!extension_.isEmpty(), extension_,
              !other.extension_.isEmpty(), other.extension_);
          lastUpdateTime_ = visitor.visitLong(lastUpdateTime_ != 0L, lastUpdateTime_,
              other.lastUpdateTime_ != 0L, other.lastUpdateTime_);
          isActive_ = visitor.visitBoolean(isActive_ != false, isActive_,
              other.isActive_ != false, other.isActive_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();

                  memberId_ = s;
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  nick_ = s;
                  break;
                }
                case 26: {
                  String s = input.readStringRequireUtf8();

                  avatar_ = s;
                  break;
                }
                case 34: {
                  String s = input.readStringRequireUtf8();

                  extension_ = s;
                  break;
                }
                case 40: {

                  lastUpdateTime_ = input.readInt64();
                  break;
                }
                case 48: {

                  isActive_ = input.readBool();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.IMUserProtos.UserInfo.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.UserInfo)
    private static final com.mc.netty.probuffer.IMUserProtos.UserInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfo();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserInfo> PARSER;

    public static com.google.protobuf.Parser<UserInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.UserInfoRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated string memberId = 1;</code>
     */
    java.util.List<String>
        getMemberIdList();
    /**
     * <code>repeated string memberId = 1;</code>
     */
    int getMemberIdCount();
    /**
     * <code>repeated string memberId = 1;</code>
     */
    java.lang.String getMemberId(int index);
    /**
     * <code>repeated string memberId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMemberIdBytes(int index);
  }
  /**
   * Protobuf type {@code wuage.UserInfoRequest}
   */
  public  static final class UserInfoRequest extends
      com.google.protobuf.GeneratedMessageLite<
          UserInfoRequest, UserInfoRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.UserInfoRequest)
      UserInfoRequestOrBuilder {
    private UserInfoRequest() {
      memberId_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    public static final int MEMBERID_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<String> memberId_;
    /**
     * <code>repeated string memberId = 1;</code>
     */
    public java.util.List<String> getMemberIdList() {
      return memberId_;
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    public int getMemberIdCount() {
      return memberId_.size();
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    public java.lang.String getMemberId(int index) {
      return memberId_.get(index);
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMemberIdBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          memberId_.get(index));
    }
    private void ensureMemberIdIsMutable() {
      if (!memberId_.isModifiable()) {
        memberId_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(memberId_);
       }
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    private void setMemberId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMemberIdIsMutable();
      memberId_.set(index, value);
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    private void addMemberId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMemberIdIsMutable();
      memberId_.add(value);
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    private void addAllMemberId(
        java.lang.Iterable<java.lang.String> values) {
      ensureMemberIdIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, memberId_);
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    private void clearMemberId() {
      memberId_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string memberId = 1;</code>
     */
    private void addMemberIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMemberIdIsMutable();
      memberId_.add(value.toStringUtf8());
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < memberId_.size(); i++) {
        output.writeString(1, memberId_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < memberId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(memberId_.get(i));
        }
        size += dataSize;
        size += 1 * getMemberIdList().size();
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.IMUserProtos.UserInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.UserInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.IMUserProtos.UserInfoRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.UserInfoRequest)
        com.mc.netty.probuffer.IMUserProtos.UserInfoRequestOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.IMUserProtos.UserInfoRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated string memberId = 1;</code>
       */
      public java.util.List<String>
          getMemberIdList() {
        return java.util.Collections.unmodifiableList(
            instance.getMemberIdList());
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public int getMemberIdCount() {
        return instance.getMemberIdCount();
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public java.lang.String getMemberId(int index) {
        return instance.getMemberId(index);
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMemberIdBytes(int index) {
        return instance.getMemberIdBytes(index);
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public Builder setMemberId(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setMemberId(index, value);
        return this;
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public Builder addMemberId(
          java.lang.String value) {
        copyOnWrite();
        instance.addMemberId(value);
        return this;
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public Builder addAllMemberId(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllMemberId(values);
        return this;
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public Builder clearMemberId() {
        copyOnWrite();
        instance.clearMemberId();
        return this;
      }
      /**
       * <code>repeated string memberId = 1;</code>
       */
      public Builder addMemberIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addMemberIdBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.UserInfoRequest)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.IMUserProtos.UserInfoRequest();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          memberId_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.IMUserProtos.UserInfoRequest other = (com.mc.netty.probuffer.IMUserProtos.UserInfoRequest) arg1;
          memberId_= visitor.visitList(memberId_, other.memberId_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readStringRequireUtf8();
                  if (!memberId_.isModifiable()) {
                    memberId_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(memberId_);
                  }
                  memberId_.add(s);
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.IMUserProtos.UserInfoRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.UserInfoRequest)
    private static final com.mc.netty.probuffer.IMUserProtos.UserInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfoRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserInfoRequest> PARSER;

    public static com.google.protobuf.Parser<UserInfoRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.UserInfoResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    boolean hasCommonInfo();
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    com.mc.netty.probuffer.CommonProtos.Common getCommonInfo();

    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    java.util.List<com.mc.netty.probuffer.IMUserProtos.UserInfo> 
        getListUserInfosList();
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    com.mc.netty.probuffer.IMUserProtos.UserInfo getListUserInfos(int index);
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    int getListUserInfosCount();
  }
  /**
   * Protobuf type {@code wuage.UserInfoResponse}
   */
  public  static final class UserInfoResponse extends
      com.google.protobuf.GeneratedMessageLite<
          UserInfoResponse, UserInfoResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.UserInfoResponse)
      UserInfoResponseOrBuilder {
    private UserInfoResponse() {
      listUserInfos_ = emptyProtobufList();
    }
    private int bitField0_;
    public static final int COMMONINFO_FIELD_NUMBER = 1;
    private com.mc.netty.probuffer.CommonProtos.Common commonInfo_;
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    public boolean hasCommonInfo() {
      return commonInfo_ != null;
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    public com.mc.netty.probuffer.CommonProtos.Common getCommonInfo() {
      return commonInfo_ == null ? com.mc.netty.probuffer.CommonProtos.Common.getDefaultInstance() : commonInfo_;
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void setCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
      if (value == null) {
        throw new NullPointerException();
      }
      commonInfo_ = value;
      
      }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void setCommonInfo(
        com.mc.netty.probuffer.CommonProtos.Common.Builder builderForValue) {
      commonInfo_ = builderForValue.build();
      
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void mergeCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
      if (commonInfo_ != null &&
          commonInfo_ != com.mc.netty.probuffer.CommonProtos.Common.getDefaultInstance()) {
        commonInfo_ =
          com.mc.netty.probuffer.CommonProtos.Common.newBuilder(commonInfo_).mergeFrom(value).buildPartial();
      } else {
        commonInfo_ = value;
      }
      
    }
    /**
     * <code>.wuage.Common commonInfo = 1;</code>
     */
    private void clearCommonInfo() {  commonInfo_ = null;
      
    }

    public static final int LISTUSERINFOS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.mc.netty.probuffer.IMUserProtos.UserInfo> listUserInfos_;
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    public java.util.List<com.mc.netty.probuffer.IMUserProtos.UserInfo> getListUserInfosList() {
      return listUserInfos_;
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    public java.util.List<? extends com.mc.netty.probuffer.IMUserProtos.UserInfoOrBuilder> 
        getListUserInfosOrBuilderList() {
      return listUserInfos_;
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    public int getListUserInfosCount() {
      return listUserInfos_.size();
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    public com.mc.netty.probuffer.IMUserProtos.UserInfo getListUserInfos(int index) {
      return listUserInfos_.get(index);
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    public com.mc.netty.probuffer.IMUserProtos.UserInfoOrBuilder getListUserInfosOrBuilder(
        int index) {
      return listUserInfos_.get(index);
    }
    private void ensureListUserInfosIsMutable() {
      if (!listUserInfos_.isModifiable()) {
        listUserInfos_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(listUserInfos_);
       }
    }

    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void setListUserInfos(
        int index, com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureListUserInfosIsMutable();
      listUserInfos_.set(index, value);
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void setListUserInfos(
        int index, com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
      ensureListUserInfosIsMutable();
      listUserInfos_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void addListUserInfos(com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureListUserInfosIsMutable();
      listUserInfos_.add(value);
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void addListUserInfos(
        int index, com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureListUserInfosIsMutable();
      listUserInfos_.add(index, value);
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void addListUserInfos(
        com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
      ensureListUserInfosIsMutable();
      listUserInfos_.add(builderForValue.build());
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void addListUserInfos(
        int index, com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
      ensureListUserInfosIsMutable();
      listUserInfos_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void addAllListUserInfos(
        java.lang.Iterable<? extends com.mc.netty.probuffer.IMUserProtos.UserInfo> values) {
      ensureListUserInfosIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, listUserInfos_);
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void clearListUserInfos() {
      listUserInfos_ = emptyProtobufList();
    }
    /**
     * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
     */
    private void removeListUserInfos(int index) {
      ensureListUserInfosIsMutable();
      listUserInfos_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (commonInfo_ != null) {
        output.writeMessage(1, getCommonInfo());
      }
      for (int i = 0; i < listUserInfos_.size(); i++) {
        output.writeMessage(2, listUserInfos_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (commonInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getCommonInfo());
      }
      for (int i = 0; i < listUserInfos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, listUserInfos_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.IMUserProtos.UserInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.UserInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.IMUserProtos.UserInfoResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.UserInfoResponse)
        com.mc.netty.probuffer.IMUserProtos.UserInfoResponseOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.IMUserProtos.UserInfoResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public boolean hasCommonInfo() {
        return instance.hasCommonInfo();
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public com.mc.netty.probuffer.CommonProtos.Common getCommonInfo() {
        return instance.getCommonInfo();
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder setCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
        copyOnWrite();
        instance.setCommonInfo(value);
        return this;
        }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder setCommonInfo(
          com.mc.netty.probuffer.CommonProtos.Common.Builder builderForValue) {
        copyOnWrite();
        instance.setCommonInfo(builderForValue);
        return this;
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder mergeCommonInfo(com.mc.netty.probuffer.CommonProtos.Common value) {
        copyOnWrite();
        instance.mergeCommonInfo(value);
        return this;
      }
      /**
       * <code>.wuage.Common commonInfo = 1;</code>
       */
      public Builder clearCommonInfo() {  copyOnWrite();
        instance.clearCommonInfo();
        return this;
      }

      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public java.util.List<com.mc.netty.probuffer.IMUserProtos.UserInfo> getListUserInfosList() {
        return java.util.Collections.unmodifiableList(
            instance.getListUserInfosList());
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public int getListUserInfosCount() {
        return instance.getListUserInfosCount();
      }/**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public com.mc.netty.probuffer.IMUserProtos.UserInfo getListUserInfos(int index) {
        return instance.getListUserInfos(index);
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder setListUserInfos(
          int index, com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
        copyOnWrite();
        instance.setListUserInfos(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder setListUserInfos(
          int index, com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setListUserInfos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder addListUserInfos(com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
        copyOnWrite();
        instance.addListUserInfos(value);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder addListUserInfos(
          int index, com.mc.netty.probuffer.IMUserProtos.UserInfo value) {
        copyOnWrite();
        instance.addListUserInfos(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder addListUserInfos(
          com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addListUserInfos(builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder addListUserInfos(
          int index, com.mc.netty.probuffer.IMUserProtos.UserInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addListUserInfos(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder addAllListUserInfos(
          java.lang.Iterable<? extends com.mc.netty.probuffer.IMUserProtos.UserInfo> values) {
        copyOnWrite();
        instance.addAllListUserInfos(values);
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder clearListUserInfos() {
        copyOnWrite();
        instance.clearListUserInfos();
        return this;
      }
      /**
       * <code>repeated .wuage.UserInfo listUserInfos = 2;</code>
       */
      public Builder removeListUserInfos(int index) {
        copyOnWrite();
        instance.removeListUserInfos(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.UserInfoResponse)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.IMUserProtos.UserInfoResponse();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          listUserInfos_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.IMUserProtos.UserInfoResponse other = (com.mc.netty.probuffer.IMUserProtos.UserInfoResponse) arg1;
          commonInfo_ = visitor.visitMessage(commonInfo_, other.commonInfo_);
          listUserInfos_= visitor.visitList(listUserInfos_, other.listUserInfos_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  com.mc.netty.probuffer.CommonProtos.Common.Builder subBuilder = null;
                  if (commonInfo_ != null) {
                    subBuilder = commonInfo_.toBuilder();
                  }
                  commonInfo_ = input.readMessage(com.mc.netty.probuffer.CommonProtos.Common.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(commonInfo_);
                    commonInfo_ = subBuilder.buildPartial();
                  }

                  break;
                }
                case 18: {
                  if (!listUserInfos_.isModifiable()) {
                    listUserInfos_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(listUserInfos_);
                  }
                  listUserInfos_.add(
                      input.readMessage(com.mc.netty.probuffer.IMUserProtos.UserInfo.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.IMUserProtos.UserInfoResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.UserInfoResponse)
    private static final com.mc.netty.probuffer.IMUserProtos.UserInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserInfoResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.IMUserProtos.UserInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserInfoResponse> PARSER;

    public static com.google.protobuf.Parser<UserInfoResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
