// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: im/Message.proto

package com.mc.netty.probuffer;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.Message)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * long型
     * </pre>
     *
     * <code>int64 messageid = 1;</code>
     */
    long getMessageid();

    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    java.lang.String getConversationId();
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    com.google.protobuf.ByteString
        getConversationIdBytes();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createAt = 3;</code>
     */
    long getCreateAt();

    /**
     * <pre>
     * 标签，用于区分业务逻辑
     * </pre>
     *
     * <code>int32 tag = 4;</code>
     */
    int getTag();

    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    java.lang.String getExtension();
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    com.google.protobuf.ByteString
        getExtensionBytes();

    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    java.lang.String getMessageContent();
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    com.google.protobuf.ByteString
        getMessageContentBytes();

    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    java.util.List<String>
        getAtOpenIdsList();
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    int getAtOpenIdsCount();
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    java.lang.String getAtOpenIds(int index);
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    com.google.protobuf.ByteString
        getAtOpenIdsBytes(int index);

    /**
     * <code>string senderId = 8;</code>
     */
    java.lang.String getSenderId();
    /**
     * <code>string senderId = 8;</code>
     */
    com.google.protobuf.ByteString
        getSenderIdBytes();

    /**
     * <pre>
     *标识conversation类型
     * </pre>
     *
     * <code>int32 conversationTag = 9;</code>
     */
    int getConversationTag();
  }
  /**
   * Protobuf type {@code wuage.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageLite<
          Message, Message.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.Message)
      MessageOrBuilder {
    private Message() {
      conversationId_ = "";
      extension_ = "";
      messageContent_ = "";
      atOpenIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
      senderId_ = "";
    }
    private int bitField0_;
    public static final int MESSAGEID_FIELD_NUMBER = 1;
    private long messageid_;
    /**
     * <pre>
     * long型
     * </pre>
     *
     * <code>int64 messageid = 1;</code>
     */
    public long getMessageid() {
      return messageid_;
    }
    /**
     * <pre>
     * long型
     * </pre>
     *
     * <code>int64 messageid = 1;</code>
     */
    private void setMessageid(long value) {
      
      messageid_ = value;
    }
    /**
     * <pre>
     * long型
     * </pre>
     *
     * <code>int64 messageid = 1;</code>
     */
    private void clearMessageid() {
      
      messageid_ = 0L;
    }

    public static final int CONVERSATIONID_FIELD_NUMBER = 2;
    private java.lang.String conversationId_;
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    public java.lang.String getConversationId() {
      return conversationId_;
    }
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getConversationIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(conversationId_);
    }
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    private void setConversationId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      conversationId_ = value;
    }
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    private void clearConversationId() {
      
      conversationId_ = getDefaultInstance().getConversationId();
    }
    /**
     * <pre>
     * 所属的会话id
     * </pre>
     *
     * <code>string conversationId = 2;</code>
     */
    private void setConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      conversationId_ = value.toStringUtf8();
    }

    public static final int CREATEAT_FIELD_NUMBER = 3;
    private long createAt_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createAt = 3;</code>
     */
    public long getCreateAt() {
      return createAt_;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createAt = 3;</code>
     */
    private void setCreateAt(long value) {
      
      createAt_ = value;
    }
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>int64 createAt = 3;</code>
     */
    private void clearCreateAt() {
      
      createAt_ = 0L;
    }

    public static final int TAG_FIELD_NUMBER = 4;
    private int tag_;
    /**
     * <pre>
     * 标签，用于区分业务逻辑
     * </pre>
     *
     * <code>int32 tag = 4;</code>
     */
    public int getTag() {
      return tag_;
    }
    /**
     * <pre>
     * 标签，用于区分业务逻辑
     * </pre>
     *
     * <code>int32 tag = 4;</code>
     */
    private void setTag(int value) {
      
      tag_ = value;
    }
    /**
     * <pre>
     * 标签，用于区分业务逻辑
     * </pre>
     *
     * <code>int32 tag = 4;</code>
     */
    private void clearTag() {
      
      tag_ = 0;
    }

    public static final int EXTENSION_FIELD_NUMBER = 5;
    private java.lang.String extension_;
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    public java.lang.String getExtension() {
      return extension_;
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(extension_);
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    private void setExtension(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extension_ = value;
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    private void clearExtension() {
      
      extension_ = getDefaultInstance().getExtension();
    }
    /**
     * <pre>
     * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
     * </pre>
     *
     * <code>string extension = 5;</code>
     */
    private void setExtensionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extension_ = value.toStringUtf8();
    }

    public static final int MESSAGECONTENT_FIELD_NUMBER = 6;
    private java.lang.String messageContent_;
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    public java.lang.String getMessageContent() {
      return messageContent_;
    }
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    public com.google.protobuf.ByteString
        getMessageContentBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(messageContent_);
    }
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    private void setMessageContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageContent_ = value;
    }
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    private void clearMessageContent() {
      
      messageContent_ = getDefaultInstance().getMessageContent();
    }
    /**
     * <pre>
     * 内容，目前只支持文字
     * </pre>
     *
     * <code>string messageContent = 6;</code>
     */
    private void setMessageContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageContent_ = value.toStringUtf8();
    }

    public static final int ATOPENIDS_FIELD_NUMBER = 7;
    private com.google.protobuf.Internal.ProtobufList<String> atOpenIds_;
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    public java.util.List<String> getAtOpenIdsList() {
      return atOpenIds_;
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    public int getAtOpenIdsCount() {
      return atOpenIds_.size();
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    public java.lang.String getAtOpenIds(int index) {
      return atOpenIds_.get(index);
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAtOpenIdsBytes(int index) {
      return com.google.protobuf.ByteString.copyFromUtf8(
          atOpenIds_.get(index));
    }
    private void ensureAtOpenIdsIsMutable() {
      if (!atOpenIds_.isModifiable()) {
        atOpenIds_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(atOpenIds_);
       }
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    private void setAtOpenIds(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAtOpenIdsIsMutable();
      atOpenIds_.set(index, value);
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    private void addAtOpenIds(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAtOpenIdsIsMutable();
      atOpenIds_.add(value);
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    private void addAllAtOpenIds(
        java.lang.Iterable<java.lang.String> values) {
      ensureAtOpenIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, atOpenIds_);
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    private void clearAtOpenIds() {
      atOpenIds_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    }
    /**
     * <code>repeated string atOpenIds = 7;</code>
     */
    private void addAtOpenIdsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAtOpenIdsIsMutable();
      atOpenIds_.add(value.toStringUtf8());
    }

    public static final int SENDERID_FIELD_NUMBER = 8;
    private java.lang.String senderId_;
    /**
     * <code>string senderId = 8;</code>
     */
    public java.lang.String getSenderId() {
      return senderId_;
    }
    /**
     * <code>string senderId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getSenderIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(senderId_);
    }
    /**
     * <code>string senderId = 8;</code>
     */
    private void setSenderId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderId_ = value;
    }
    /**
     * <code>string senderId = 8;</code>
     */
    private void clearSenderId() {
      
      senderId_ = getDefaultInstance().getSenderId();
    }
    /**
     * <code>string senderId = 8;</code>
     */
    private void setSenderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderId_ = value.toStringUtf8();
    }

    public static final int CONVERSATIONTAG_FIELD_NUMBER = 9;
    private int conversationTag_;
    /**
     * <pre>
     *标识conversation类型
     * </pre>
     *
     * <code>int32 conversationTag = 9;</code>
     */
    public int getConversationTag() {
      return conversationTag_;
    }
    /**
     * <pre>
     *标识conversation类型
     * </pre>
     *
     * <code>int32 conversationTag = 9;</code>
     */
    private void setConversationTag(int value) {
      
      conversationTag_ = value;
    }
    /**
     * <pre>
     *标识conversation类型
     * </pre>
     *
     * <code>int32 conversationTag = 9;</code>
     */
    private void clearConversationTag() {
      
      conversationTag_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageid_ != 0L) {
        output.writeInt64(1, messageid_);
      }
      if (!conversationId_.isEmpty()) {
        output.writeString(2, getConversationId());
      }
      if (createAt_ != 0L) {
        output.writeInt64(3, createAt_);
      }
      if (tag_ != 0) {
        output.writeInt32(4, tag_);
      }
      if (!extension_.isEmpty()) {
        output.writeString(5, getExtension());
      }
      if (!messageContent_.isEmpty()) {
        output.writeString(6, getMessageContent());
      }
      for (int i = 0; i < atOpenIds_.size(); i++) {
        output.writeString(7, atOpenIds_.get(i));
      }
      if (!senderId_.isEmpty()) {
        output.writeString(8, getSenderId());
      }
      if (conversationTag_ != 0) {
        output.writeInt32(9, conversationTag_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (messageid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, messageid_);
      }
      if (!conversationId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getConversationId());
      }
      if (createAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, createAt_);
      }
      if (tag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, tag_);
      }
      if (!extension_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getExtension());
      }
      if (!messageContent_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getMessageContent());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < atOpenIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(atOpenIds_.get(i));
        }
        size += dataSize;
        size += 1 * getAtOpenIdsList().size();
      }
      if (!senderId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getSenderId());
      }
      if (conversationTag_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, conversationTag_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.MessageProtos.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.MessageProtos.Message, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.Message)
        com.mc.netty.probuffer.MessageProtos.MessageOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.MessageProtos.Message.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * long型
       * </pre>
       *
       * <code>int64 messageid = 1;</code>
       */
      public long getMessageid() {
        return instance.getMessageid();
      }
      /**
       * <pre>
       * long型
       * </pre>
       *
       * <code>int64 messageid = 1;</code>
       */
      public Builder setMessageid(long value) {
        copyOnWrite();
        instance.setMessageid(value);
        return this;
      }
      /**
       * <pre>
       * long型
       * </pre>
       *
       * <code>int64 messageid = 1;</code>
       */
      public Builder clearMessageid() {
        copyOnWrite();
        instance.clearMessageid();
        return this;
      }

      /**
       * <pre>
       * 所属的会话id
       * </pre>
       *
       * <code>string conversationId = 2;</code>
       */
      public java.lang.String getConversationId() {
        return instance.getConversationId();
      }
      /**
       * <pre>
       * 所属的会话id
       * </pre>
       *
       * <code>string conversationId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getConversationIdBytes() {
        return instance.getConversationIdBytes();
      }
      /**
       * <pre>
       * 所属的会话id
       * </pre>
       *
       * <code>string conversationId = 2;</code>
       */
      public Builder setConversationId(
          java.lang.String value) {
        copyOnWrite();
        instance.setConversationId(value);
        return this;
      }
      /**
       * <pre>
       * 所属的会话id
       * </pre>
       *
       * <code>string conversationId = 2;</code>
       */
      public Builder clearConversationId() {
        copyOnWrite();
        instance.clearConversationId();
        return this;
      }
      /**
       * <pre>
       * 所属的会话id
       * </pre>
       *
       * <code>string conversationId = 2;</code>
       */
      public Builder setConversationIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setConversationIdBytes(value);
        return this;
      }

      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int64 createAt = 3;</code>
       */
      public long getCreateAt() {
        return instance.getCreateAt();
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int64 createAt = 3;</code>
       */
      public Builder setCreateAt(long value) {
        copyOnWrite();
        instance.setCreateAt(value);
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>int64 createAt = 3;</code>
       */
      public Builder clearCreateAt() {
        copyOnWrite();
        instance.clearCreateAt();
        return this;
      }

      /**
       * <pre>
       * 标签，用于区分业务逻辑
       * </pre>
       *
       * <code>int32 tag = 4;</code>
       */
      public int getTag() {
        return instance.getTag();
      }
      /**
       * <pre>
       * 标签，用于区分业务逻辑
       * </pre>
       *
       * <code>int32 tag = 4;</code>
       */
      public Builder setTag(int value) {
        copyOnWrite();
        instance.setTag(value);
        return this;
      }
      /**
       * <pre>
       * 标签，用于区分业务逻辑
       * </pre>
       *
       * <code>int32 tag = 4;</code>
       */
      public Builder clearTag() {
        copyOnWrite();
        instance.clearTag();
        return this;
      }

      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 5;</code>
       */
      public java.lang.String getExtension() {
        return instance.getExtension();
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 5;</code>
       */
      public com.google.protobuf.ByteString
          getExtensionBytes() {
        return instance.getExtensionBytes();
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 5;</code>
       */
      public Builder setExtension(
          java.lang.String value) {
        copyOnWrite();
        instance.setExtension(value);
        return this;
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 5;</code>
       */
      public Builder clearExtension() {
        copyOnWrite();
        instance.clearExtension();
        return this;
      }
      /**
       * <pre>
       * 用户自定义字段，可自己控制其内容，建议存入json对象化数据
       * </pre>
       *
       * <code>string extension = 5;</code>
       */
      public Builder setExtensionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setExtensionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 内容，目前只支持文字
       * </pre>
       *
       * <code>string messageContent = 6;</code>
       */
      public java.lang.String getMessageContent() {
        return instance.getMessageContent();
      }
      /**
       * <pre>
       * 内容，目前只支持文字
       * </pre>
       *
       * <code>string messageContent = 6;</code>
       */
      public com.google.protobuf.ByteString
          getMessageContentBytes() {
        return instance.getMessageContentBytes();
      }
      /**
       * <pre>
       * 内容，目前只支持文字
       * </pre>
       *
       * <code>string messageContent = 6;</code>
       */
      public Builder setMessageContent(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessageContent(value);
        return this;
      }
      /**
       * <pre>
       * 内容，目前只支持文字
       * </pre>
       *
       * <code>string messageContent = 6;</code>
       */
      public Builder clearMessageContent() {
        copyOnWrite();
        instance.clearMessageContent();
        return this;
      }
      /**
       * <pre>
       * 内容，目前只支持文字
       * </pre>
       *
       * <code>string messageContent = 6;</code>
       */
      public Builder setMessageContentBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageContentBytes(value);
        return this;
      }

      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public java.util.List<String>
          getAtOpenIdsList() {
        return java.util.Collections.unmodifiableList(
            instance.getAtOpenIdsList());
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public int getAtOpenIdsCount() {
        return instance.getAtOpenIdsCount();
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public java.lang.String getAtOpenIds(int index) {
        return instance.getAtOpenIds(index);
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAtOpenIdsBytes(int index) {
        return instance.getAtOpenIdsBytes(index);
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public Builder setAtOpenIds(
          int index, java.lang.String value) {
        copyOnWrite();
        instance.setAtOpenIds(index, value);
        return this;
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public Builder addAtOpenIds(
          java.lang.String value) {
        copyOnWrite();
        instance.addAtOpenIds(value);
        return this;
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public Builder addAllAtOpenIds(
          java.lang.Iterable<java.lang.String> values) {
        copyOnWrite();
        instance.addAllAtOpenIds(values);
        return this;
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public Builder clearAtOpenIds() {
        copyOnWrite();
        instance.clearAtOpenIds();
        return this;
      }
      /**
       * <code>repeated string atOpenIds = 7;</code>
       */
      public Builder addAtOpenIdsBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.addAtOpenIdsBytes(value);
        return this;
      }

      /**
       * <code>string senderId = 8;</code>
       */
      public java.lang.String getSenderId() {
        return instance.getSenderId();
      }
      /**
       * <code>string senderId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getSenderIdBytes() {
        return instance.getSenderIdBytes();
      }
      /**
       * <code>string senderId = 8;</code>
       */
      public Builder setSenderId(
          java.lang.String value) {
        copyOnWrite();
        instance.setSenderId(value);
        return this;
      }
      /**
       * <code>string senderId = 8;</code>
       */
      public Builder clearSenderId() {
        copyOnWrite();
        instance.clearSenderId();
        return this;
      }
      /**
       * <code>string senderId = 8;</code>
       */
      public Builder setSenderIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSenderIdBytes(value);
        return this;
      }

      /**
       * <pre>
       *标识conversation类型
       * </pre>
       *
       * <code>int32 conversationTag = 9;</code>
       */
      public int getConversationTag() {
        return instance.getConversationTag();
      }
      /**
       * <pre>
       *标识conversation类型
       * </pre>
       *
       * <code>int32 conversationTag = 9;</code>
       */
      public Builder setConversationTag(int value) {
        copyOnWrite();
        instance.setConversationTag(value);
        return this;
      }
      /**
       * <pre>
       *标识conversation类型
       * </pre>
       *
       * <code>int32 conversationTag = 9;</code>
       */
      public Builder clearConversationTag() {
        copyOnWrite();
        instance.clearConversationTag();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.Message)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.MessageProtos.Message();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          atOpenIds_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.MessageProtos.Message other = (com.mc.netty.probuffer.MessageProtos.Message) arg1;
          messageid_ = visitor.visitLong(messageid_ != 0L, messageid_,
              other.messageid_ != 0L, other.messageid_);
          conversationId_ = visitor.visitString(!conversationId_.isEmpty(), conversationId_,
              !other.conversationId_.isEmpty(), other.conversationId_);
          createAt_ = visitor.visitLong(createAt_ != 0L, createAt_,
              other.createAt_ != 0L, other.createAt_);
          tag_ = visitor.visitInt(tag_ != 0, tag_,
              other.tag_ != 0, other.tag_);
          extension_ = visitor.visitString(!extension_.isEmpty(), extension_,
              !other.extension_.isEmpty(), other.extension_);
          messageContent_ = visitor.visitString(!messageContent_.isEmpty(), messageContent_,
              !other.messageContent_.isEmpty(), other.messageContent_);
          atOpenIds_= visitor.visitList(atOpenIds_, other.atOpenIds_);
          senderId_ = visitor.visitString(!senderId_.isEmpty(), senderId_,
              !other.senderId_.isEmpty(), other.senderId_);
          conversationTag_ = visitor.visitInt(conversationTag_ != 0, conversationTag_,
              other.conversationTag_ != 0, other.conversationTag_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 8: {

                  messageid_ = input.readInt64();
                  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  conversationId_ = s;
                  break;
                }
                case 24: {

                  createAt_ = input.readInt64();
                  break;
                }
                case 32: {

                  tag_ = input.readInt32();
                  break;
                }
                case 42: {
                  String s = input.readStringRequireUtf8();

                  extension_ = s;
                  break;
                }
                case 50: {
                  String s = input.readStringRequireUtf8();

                  messageContent_ = s;
                  break;
                }
                case 58: {
                  String s = input.readStringRequireUtf8();
                  if (!atOpenIds_.isModifiable()) {
                    atOpenIds_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(atOpenIds_);
                  }
                  atOpenIds_.add(s);
                  break;
                }
                case 66: {
                  String s = input.readStringRequireUtf8();

                  senderId_ = s;
                  break;
                }
                case 72: {

                  conversationTag_ = input.readInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.MessageProtos.Message.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.Message)
    private static final com.mc.netty.probuffer.MessageProtos.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Message();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.MessageProtos.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Message> PARSER;

    public static com.google.protobuf.Parser<Message> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MessageNotificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:wuage.MessageNotification)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    java.util.List<com.mc.netty.probuffer.MessageProtos.Message> 
        getAddedListList();
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    com.mc.netty.probuffer.MessageProtos.Message getAddedList(int index);
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    int getAddedListCount();

    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    java.util.List<com.mc.netty.probuffer.MessageProtos.Message> 
        getRemovedListList();
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    com.mc.netty.probuffer.MessageProtos.Message getRemovedList(int index);
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    int getRemovedListCount();
  }
  /**
   * Protobuf type {@code wuage.MessageNotification}
   */
  public  static final class MessageNotification extends
      com.google.protobuf.GeneratedMessageLite<
          MessageNotification, MessageNotification.Builder> implements
      // @@protoc_insertion_point(message_implements:wuage.MessageNotification)
      MessageNotificationOrBuilder {
    private MessageNotification() {
      addedList_ = emptyProtobufList();
      removedList_ = emptyProtobufList();
    }
    public static final int ADDEDLIST_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.mc.netty.probuffer.MessageProtos.Message> addedList_;
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    public java.util.List<com.mc.netty.probuffer.MessageProtos.Message> getAddedListList() {
      return addedList_;
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    public java.util.List<? extends com.mc.netty.probuffer.MessageProtos.MessageOrBuilder> 
        getAddedListOrBuilderList() {
      return addedList_;
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    public int getAddedListCount() {
      return addedList_.size();
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    public com.mc.netty.probuffer.MessageProtos.Message getAddedList(int index) {
      return addedList_.get(index);
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    public com.mc.netty.probuffer.MessageProtos.MessageOrBuilder getAddedListOrBuilder(
        int index) {
      return addedList_.get(index);
    }
    private void ensureAddedListIsMutable() {
      if (!addedList_.isModifiable()) {
        addedList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(addedList_);
       }
    }

    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void setAddedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAddedListIsMutable();
      addedList_.set(index, value);
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void setAddedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureAddedListIsMutable();
      addedList_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void addAddedList(com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAddedListIsMutable();
      addedList_.add(value);
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void addAddedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAddedListIsMutable();
      addedList_.add(index, value);
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void addAddedList(
        com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureAddedListIsMutable();
      addedList_.add(builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void addAddedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureAddedListIsMutable();
      addedList_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void addAllAddedList(
        java.lang.Iterable<? extends com.mc.netty.probuffer.MessageProtos.Message> values) {
      ensureAddedListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, addedList_);
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void clearAddedList() {
      addedList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .wuage.Message addedList = 1;</code>
     */
    private void removeAddedList(int index) {
      ensureAddedListIsMutable();
      addedList_.remove(index);
    }

    public static final int REMOVEDLIST_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<com.mc.netty.probuffer.MessageProtos.Message> removedList_;
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    public java.util.List<com.mc.netty.probuffer.MessageProtos.Message> getRemovedListList() {
      return removedList_;
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    public java.util.List<? extends com.mc.netty.probuffer.MessageProtos.MessageOrBuilder> 
        getRemovedListOrBuilderList() {
      return removedList_;
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    public int getRemovedListCount() {
      return removedList_.size();
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    public com.mc.netty.probuffer.MessageProtos.Message getRemovedList(int index) {
      return removedList_.get(index);
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    public com.mc.netty.probuffer.MessageProtos.MessageOrBuilder getRemovedListOrBuilder(
        int index) {
      return removedList_.get(index);
    }
    private void ensureRemovedListIsMutable() {
      if (!removedList_.isModifiable()) {
        removedList_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(removedList_);
       }
    }

    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void setRemovedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRemovedListIsMutable();
      removedList_.set(index, value);
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void setRemovedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureRemovedListIsMutable();
      removedList_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void addRemovedList(com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRemovedListIsMutable();
      removedList_.add(value);
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void addRemovedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRemovedListIsMutable();
      removedList_.add(index, value);
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void addRemovedList(
        com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureRemovedListIsMutable();
      removedList_.add(builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void addRemovedList(
        int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
      ensureRemovedListIsMutable();
      removedList_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void addAllRemovedList(
        java.lang.Iterable<? extends com.mc.netty.probuffer.MessageProtos.Message> values) {
      ensureRemovedListIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, removedList_);
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void clearRemovedList() {
      removedList_ = emptyProtobufList();
    }
    /**
     * <code>repeated .wuage.Message removedList = 2;</code>
     */
    private void removeRemovedList(int index) {
      ensureRemovedListIsMutable();
      removedList_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < addedList_.size(); i++) {
        output.writeMessage(1, addedList_.get(i));
      }
      for (int i = 0; i < removedList_.size(); i++) {
        output.writeMessage(2, removedList_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < addedList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, addedList_.get(i));
      }
      for (int i = 0; i < removedList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, removedList_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.mc.netty.probuffer.MessageProtos.MessageNotification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mc.netty.probuffer.MessageProtos.MessageNotification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code wuage.MessageNotification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.mc.netty.probuffer.MessageProtos.MessageNotification, Builder> implements
        // @@protoc_insertion_point(builder_implements:wuage.MessageNotification)
        com.mc.netty.probuffer.MessageProtos.MessageNotificationOrBuilder {
      // Construct using com.wuage.steelim.center.common.probuffer.MessageProtos.MessageNotification.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public java.util.List<com.mc.netty.probuffer.MessageProtos.Message> getAddedListList() {
        return java.util.Collections.unmodifiableList(
            instance.getAddedListList());
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public int getAddedListCount() {
        return instance.getAddedListCount();
      }/**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public com.mc.netty.probuffer.MessageProtos.Message getAddedList(int index) {
        return instance.getAddedList(index);
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder setAddedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.setAddedList(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder setAddedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.setAddedList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder addAddedList(com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.addAddedList(value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder addAddedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.addAddedList(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder addAddedList(
          com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.addAddedList(builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder addAddedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.addAddedList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder addAllAddedList(
          java.lang.Iterable<? extends com.mc.netty.probuffer.MessageProtos.Message> values) {
        copyOnWrite();
        instance.addAllAddedList(values);
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder clearAddedList() {
        copyOnWrite();
        instance.clearAddedList();
        return this;
      }
      /**
       * <code>repeated .wuage.Message addedList = 1;</code>
       */
      public Builder removeAddedList(int index) {
        copyOnWrite();
        instance.removeAddedList(index);
        return this;
      }

      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public java.util.List<com.mc.netty.probuffer.MessageProtos.Message> getRemovedListList() {
        return java.util.Collections.unmodifiableList(
            instance.getRemovedListList());
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public int getRemovedListCount() {
        return instance.getRemovedListCount();
      }/**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public com.mc.netty.probuffer.MessageProtos.Message getRemovedList(int index) {
        return instance.getRemovedList(index);
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder setRemovedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.setRemovedList(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder setRemovedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.setRemovedList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder addRemovedList(com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.addRemovedList(value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder addRemovedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message value) {
        copyOnWrite();
        instance.addRemovedList(index, value);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder addRemovedList(
          com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.addRemovedList(builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder addRemovedList(
          int index, com.mc.netty.probuffer.MessageProtos.Message.Builder builderForValue) {
        copyOnWrite();
        instance.addRemovedList(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder addAllRemovedList(
          java.lang.Iterable<? extends com.mc.netty.probuffer.MessageProtos.Message> values) {
        copyOnWrite();
        instance.addAllRemovedList(values);
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder clearRemovedList() {
        copyOnWrite();
        instance.clearRemovedList();
        return this;
      }
      /**
       * <code>repeated .wuage.Message removedList = 2;</code>
       */
      public Builder removeRemovedList(int index) {
        copyOnWrite();
        instance.removeRemovedList(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:wuage.MessageNotification)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.mc.netty.probuffer.MessageProtos.MessageNotification();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          addedList_.makeImmutable();
          removedList_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.mc.netty.probuffer.MessageProtos.MessageNotification other = (com.mc.netty.probuffer.MessageProtos.MessageNotification) arg1;
          addedList_= visitor.visitList(addedList_, other.addedList_);
          removedList_= visitor.visitList(removedList_, other.removedList_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!addedList_.isModifiable()) {
                    addedList_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(addedList_);
                  }
                  addedList_.add(
                      input.readMessage(com.mc.netty.probuffer.MessageProtos.Message.parser(), extensionRegistry));
                  break;
                }
                case 18: {
                  if (!removedList_.isModifiable()) {
                    removedList_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(removedList_);
                  }
                  removedList_.add(
                      input.readMessage(com.mc.netty.probuffer.MessageProtos.Message.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.mc.netty.probuffer.MessageProtos.MessageNotification.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:wuage.MessageNotification)
    private static final com.mc.netty.probuffer.MessageProtos.MessageNotification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageNotification();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.mc.netty.probuffer.MessageProtos.MessageNotification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MessageNotification> PARSER;

    public static com.google.protobuf.Parser<MessageNotification> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
